加入断开连接事件
dotnet-campus/dotnetCampus.Ipc pull request #28
Opened 2020-11-22 10:16 UTC by lindexi

2020-11-22 14:01 UTC, walterlv requested changes

2020-11-22 14:01 UTC, walterlv commented on demo/dotnetCampus.Ipc.WpfDemo/DispatcherSwitcher.cs
> +        public class DispatcherAwaiter : INotifyCompletion
这个版本有点 bug，就是如果已经是 UI 线程了，这个也会 InvokeAsync 一下

2020-11-22 14:01 UTC, walterlv commented on src/dotnetCampus.Ipc.Abstractions/IPeerProxy.cs
> +        event EventHandler<IPeerConnectBreakArgs> PeerConnectBroke;
Broke 是个动词，要用完成时态。前面的 Connect 是个动词，要用动名词。

PeerConnectionBroken

2020-11-22 14:01 UTC, walterlv commented on src/dotnetCampus.Ipc.Abstractions/Context/IPeerConnectBreakArgs.cs
> +    public interface IPeerConnectBreakArgs
IPeerConnectionBrokenArgs

2020-11-22 14:01 UTC, walterlv commented on src/dotnetCampus.Ipc.Abstractions/Context/IpcBufferMessage.cs
> +    public readonly struct IpcBufferMessage
这种的，一般用 IDE 生成一下 Equals

2020-11-22 14:01 UTC, walterlv commented on src/dotnetCampus.Ipc.PipeCore/Context/EventArgs_/PeerConnectBreakArgs.cs
> +    public class PeerConnectBreakArgs : EventArgs, IPeerConnectBreakArgs
一并

2020-11-22 14:01 UTC, walterlv commented on src/dotnetCampus.Ipc.Abstractions/Context/IpcBufferMessage.cs
> +﻿namespace dotnetCampus.Ipc.Abstractions.Context
借个位置聊个天……还是不建议把类名放到命名空间中……

2020-11-23 00:58 UTC, lindexi commented on demo/dotnetCampus.Ipc.WpfDemo/DispatcherSwitcher.cs
> +        public class DispatcherAwaiter : INotifyCompletion
@walterlv demo 无视

2020-11-23 02:57 UTC, lindexi commented on src/dotnetCampus.Ipc.Abstractions/Context/IpcBufferMessage.cs
> +    public readonly struct IpcBufferMessage
@walterlv 没需求

2020-11-27 06:21 UTC, merged