wip: 尝试加入远程调用
dotnet-campus/dotnetCampus.Ipc pull request #29
Opened 2020-11-22 13:08 UTC by lindexi

等待 https://github.com/dotnet-campus/dotnetCampus.Ipc/pull/28

2020-11-28 07:17 UTC, walterlv requested changes

2020-11-28 07:17 UTC, walterlv commented on src/dotnetCampus.Ipc/IpcProxy.cs
> +#if !NETCOREAPP
这个条件判断，是多余的吧？

2020-11-28 07:17 UTC, walterlv commented on src/dotnetCampus.Ipc/IpcProxy.cs
> +            throw new ArgumentException($"方法返回值只能是 Task 或 Task 泛形");
泛型

2020-11-28 07:17 UTC, walterlv commented on src/dotnetCampus.Ipc/IpcClientProvider.cs
> +        public IPeerProxy PeerProxy { set; get; } = null!;
不建议习惯这种欺骗编译器的做法，建议真实反映当时的空性。

2020-11-28 07:17 UTC, walterlv commented on src/dotnetCampus.Ipc/IpcProxy.cs
> +            return default!;
既然声明不会返回 null，请不要传 null。

2020-12-03 00:46 UTC, lindexi commented on src/dotnetCampus.Ipc/IpcProxy.cs
> +#if !NETCOREAPP
@walterlv 这是必要的

2020-12-03 00:47 UTC, lindexi commented on src/dotnetCampus.Ipc/IpcClientProvider.cs
> +        public IPeerProxy PeerProxy { set; get; } = null!;
@walterlv 用的时候，这个属性一定不是空

2020-12-03 00:47 UTC, lindexi commented on src/dotnetCampus.Ipc/IpcProxy.cs
> +            return default!;
@walterlv 此时就应该返回空，空是预期

2020-12-04 07:50 UTC, walterlv approved these changes

2020-12-04 07:50 UTC, merged