干掉 ACK 的方式
dotnet-campus/dotnetCampus.Ipc pull request #32
Opened 2021-06-22 00:44 UTC by lindexi

原因是管道的发送，如果能发送成功，就是对方收到消息

2021-06-22 02:08 UTC, walterlv requested changes

2021-06-22 02:08 UTC, walterlv commented on src/dotnetCampus.Ipc.PipeCore/Context/IpcMessageCommandType.cs
> +        Business = (1 << 16 - 1),
直接写 15 很直观了，写 16-1 还容易让大家看错优先级

2021-06-22 02:08 UTC, walterlv commented on src/dotnetCampus.Ipc.PipeCore/Core_/IpcProvider.cs
> +            if (IpcServerService != null!) return;
我还是觉得你的空分析器有毒，`null!` 根本不是个正常的写法

2021-06-26 13:08 UTC, walterlv requested changes

2021-06-26 13:08 UTC, walterlv commented on src/dotnetCampus.Ipc.PipeCore/Core_/IpcClientService.cs
> +            if (IsDisposed)
这里，你可能需要考虑使用线程安全版本的 Dispose 模式

2021-06-26 13:12 UTC, lindexi commented on src/dotnetCampus.Ipc.PipeCore/Core_/IpcClientService.cs
> +            if (IsDisposed)
@walterlv 这里暂时无视线程安全问题，原因是断开和结束，都是很非预期的行为了

2021-06-26 13:12 UTC, merged

2021-06-26 13:13 UTC, lindexi commented on src/dotnetCampus.Ipc.PipeCore/Core_/IpcClientService.cs
> +            if (IsDisposed)
@walterlv 在结束的时候，做线程安全，这里看起来是需要做一条链的代码。暂时先不在这个 PR 做这个